### ISSUE TITLE
New version on nuget

### ISSUE THREAD

**Issue by jgasiorowski** [stevenbey/elfar#3]
I don't know if this is right place to ask question. 
When this version will find its place on nuget repository? I'm still using v 1.2 where Cookie collection is Dictionary and handled exception logging have to be handled by extension methods to Exception object (taken and updated on source forge).

I understand that I can download any version from here but nuget is way more easier to maintain in project.

Thanks really much. Great work

**Comment by tiesont** [comment]
Given that this is still outdated, would you be interested in a volunteer to update the package?

**Comment by stevenbey** [comment]
Sorry for the delay in responding.  I welcome any input that you'd like to make.

**Comment by tiesont** [comment]
Okay. How do you want to accomplish that? I would either need publish permission on your NuGet package, or you can tell me how you'd prefer to receive an updated .nupkg file.

**Comment by stevenbey** [comment]
I've set up an API Key, so that you can update the ELFAR packages.  Is it OK for me to email you the key?

From nuget.org: The following snippet demonstrates how you can use the NuGet command-line utility to submit a NuGet package to the gallery:

nuget.exe setApiKey [your API key]
nuget.exe push MyPackage.1.0.nupkg -Source https://www.nuget.org/api/v2/package

Many thanks

**Comment by tiesont** [comment]
Yes, email is fine.

I tend to use NuGet Package Explorer to publish packages, since it also lets me build the package itself (I've never bothered to setup a build script - yay, manual labor).

**Comment by stevenbey** [comment]
Email sent. :)

To be honest, I tend to use the NuGet Package Explorer too.

I did have some PowerShell scripts to generate synchronised packages but they're on one of my old machines.

Anyway, many thanks for all of your help.
